# Generated by Django 4.2.6 on 2023-10-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "portfolio",
            "0002_remove_blogpost_picture_alter_gallery_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="image",
            field=models.ImageField(upload_to="gallery_images/"),
        ),
    ]
