# Generated by Django 4.2.6 on 2023-10-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0003_alter_gallery_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogimage",
            name="image",
            field=models.ImageField(upload_to="media/blogPost_images/"),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="image",
            field=models.ImageField(upload_to="media/gallery_images/"),
        ),
    ]
