# Generated by Django 4.2.6 on 2023-10-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0006_alter_blogimage_image_alter_gallery_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogimage",
            name="image",
            field=models.ImageField(upload_to="blogPost_images/"),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="image",
            field=models.ImageField(upload_to="gallery_images/"),
        ),
    ]
