# Generated by Django 4.2.6 on 2023-10-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0007_alter_blogimage_image_alter_gallery_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="description",
            field=models.TextField(default="description goes here...", max_length=150),
            preserve_default=False,
        ),
    ]
